language: node_js
node_js:
  - "node"
os:
  - linux
script:
  - yarn test
after_script:
  # custome upcloud script should go here. More info https://docs.travis-ci.com/user/deployment/custom/
notifications:
  slack:
    on_failure: always