language: node_js
node_js:
  - node
os:
  - linux
cache:
  yarn: true
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - yarn test
notifications:
  slack:
    on_success: never
    on_failure: always
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master
