language: node_js
node_js:
  - "node"
os:
  - linux
script:
  - yarn test
after_script:
  # Custome upcloud script should go here. More info https://docs.travis-ci.com/user/deployment/custom/
  # For encrypting keys: https://docs.travis-ci.com/user/encrypting-files/
notifications:
  slack:
    on_failure: always