language: node_js
node_js:
- node
os:
- linux
script:
- yarn test
notifications:
  slack:
    on_success: never
    on_failure: always
deploy:
  provider: script
  script: deploy.sh
  on:
    branch: master
